### ISSUE TITLE
What if the user is already running the latest version?

### ISSUE THREAD

**Issue by jgstew** [scriptingosx/Installomator#1]
What happens if I trigger Installomator on a system that happens to already be running the latest version?

Does it download the software anyway, since it may need to do that to know if the version is latest?

Does it try to install the software regardless?

I'm wondering how careful you should be in NOT scheduling this to trigger too often on a schedule if you don't know if the user needs the update. Would be nice to document this aspect.

I did read over the code, but couldn't quite tell what happens. I haven't tested it yet, but would like to do so.

It would be interesting to save etag data for the downloads somewhere and check that BEFORE redownloading the software again, but perhaps with a flag to force reinstall.

**Comment by scriptingosx** [comment]
Yes, the software will be downloaded anyway and installed over the existing installation. 

(Exceptions are the applications that have an updateTool, see documentation.)

Our workflow is to control the execution of the script with smart groups in Jamf. Or to provide the policy in Self Service, so it is user initiated and then a re-installation, even when it is the same version may be a useful trouble-shooting tool.

Saving the tag would not be possible for all downloads. Overall, I think it might be easier to control script/policy execution within the management system.

But if you think it would be useful and can make etag storage work, I'd love a pull request.

**Comment by jgstew** [comment]
Also, part of my reason for this issue was to get the answer, but also to update the documentation to reflect the answer. Thanks for taking the time to answer this.
