### ISSUE TITLE
Webex Teams now "Webex"

### ISSUE THREAD

**Issue by timelost11** [scriptingosx/Installomator#101]
Found out that the Webex Teams app is now just called "Webex".

I was able to update the installomator script with the following to allow the installation to work with the new name.

By changing name to "Webex" from "Webex Teams" the install is now running successfully again.

webexteams)
    # credit: Erik Stam (@erikstam)
    name="Webex"
    type="dmg"
    downloadURL="https://binaries.webex.com/WebexTeamsDesktop-MACOS-Gold/WebexTeams.dmg"
    expectedTeamID="DE8Y96K9QP"
    ;;

**Comment by scriptingosx** [comment]
thank you!
