### ISSUE TITLE
Support for universal apps

### ISSUE THREAD

**Issue by khikita** [scriptingosx/Installomator#104]
If you have an app that is already supported by Apple silicon, you can use it.
If there are apps that are already compatible with Apple silicon, 
please make it possible to automatically determine the CPU and automatically install and update apps with the appropriate architecture.

**Comment by Theile** [comment]
I don't Have an example of an app that needs this, but in case there is, this ca be put inside the label in the case statement:
`
    if [[ $(arch) == "arm64" ]]; then
      downloadURL=http://URL/arm
    elif [[ $(arch) == "i386" ]]; then
      downloadURL=http://URL/intel
    fi `
So for these special cases we do not need anything from Installomator.

**Comment by Theile** [comment]
We have worked on dev 0.5. Several software labels have the arch-check to differentiate between arm and intel. There is no strict rule used. Som developers offers the universal version as something special for M1, where the intel-version is default, some just offers the universal version default. Some have different versions for intel and arm. Some even differentiate the version numbers between these.
As far as Installomator is concerned it just installs the software in the downloadURL.
See the labels: vlc, googlechrome etc. This is also mentioned in the README.
If you encounter software, that are missing, please let us know. I will go ahead and close this now.
Thank you!
