### ISSUE TITLE
Examples of bypassing Login Auth URLS

### ISSUE THREAD

**Issue by grainofric3** [scriptingosx/Installomator#139]
Are there any examples (hopefully none that I missed) that show how to bypass auth via the Curl command?

I was redirected here as an option to download/automate Jamf Connect but I cant find anything on the forums on this GH that shows how its possible since theres a login token (or something of that nature) that is appended to the download URL

**Comment by Theile** [comment]
If you mean in a server that will append this key in order to authorize the download, then it's not possible. Only the server can create that key. 

If you want to post a login before downloading, then that can be done, but I don't think we have any examples.

**Comment by grainofric3** [comment]
thanks reasonable and i figured as much - someone on jamfnation has it working somehow but hasnt shared how so I figured id post here. 

thank you!
