### ISSUE TITLE
getAppVersion never finds anything

### ISSUE THREAD

**Issue by Theile** [scriptingosx/Installomator#15]
There is an error in the `mdfind` command in the `getAppVersion` function.
The `applist` variable should be defined like this:
`applist=$(mdfind "kMDItemFSName='$appName' kMDItemKind='Application'" -0 )`
The double "`&&`" should be eliminated. At least on my system, it never finds any app.

**Comment by scriptingosx** [comment]
fixed in e4e9aec0e2d39ee8cd148305dd4e52e7b913420f
