### ISSUE TITLE
getAppVersion function-call in the bottom does not give any result

### ISSUE THREAD

**Issue by Theile** [scriptingosx/Installomator#16]
After my fix for `mdfind` I was wandering why the `getAppVersion` call in the bottom of the script does not find the newly installed app.

I had to add a `sleep 2` line before. I guess the indexing is not done after the copy. I do not know if 2 seconds are enough, or a better check for the indexing should be done.

**Comment by scriptingosx** [comment]
I think want to move away from `mdfind` to determine the version number.

**Comment by scriptingosx** [comment]
added a delay before reading the new version, fixed in e4e9aec0e2d39ee8cd148305dd4e52e7b913420f
