### ISSUE TITLE
Atom Team ID error

### ISSUE THREAD

**Issue by bbenkle** [scriptingosx/Installomator#35]
I get a Team ID mismatch error when running the Atom install. The Application itself if downloaded and installed independently reports the same Team ID as the one in the script. So I am unsure where the mismatch is occurring. 

<img width="875" alt="Atom_installer" src="https://user-images.githubusercontent.com/34138385/86397665-43eb2900-bc72-11ea-89f1-e50b71a3176c.png">

**Comment by scriptingosx** [comment]
This was a problem with using `tar` to expand on Mojave. Fixed in dev with commit ee91690a0da63aacd59777c9f0301f6b7558d81c
