### ISSUE TITLE
Add variables to customize user quit & update prompt message

### ISSUE THREAD

**Issue by apizz** [scriptingosx/Installomator#72]
Building on the idea of adding variables for notifications (https://github.com/scriptingosx/Installomator/issues/70), would like to see the the prompt message displayed to users if the app attempting to be updated is detected as running (https://github.com/scriptingosx/Installomator/blob/dev/Installomator.sh#L1154-L1155) be turned into a variable so this can be customized, if `BLOCKING_PROCESS_ACTION=prompt_user`

**Comment by scriptingosx** [comment]
see `argument-refactor` branch for an implementation of this
