### ISSUE TITLE
Brave download is broken

### ISSUE THREAD

**Issue by apizz** [scriptingosx/Installomator#76]
Current URL is listed as `https://laptop-updates.brave.com/latest/osx`, but this is a redirect to `https://brave-browser-downloads.s3.brave.com/latest/Brave-Browser.dmg`.

Not sure if it's best to change to the latter URL.  I tried substituting the current URL for `$(curl -fs https://laptop-updates.brave.com/latest/osx)` but did not complete successfully.

**Comment by apizz** [comment]
It appears the Team IDs may have changed as well?

I'm getting the following from latest download: `KL8N8XSYF4`

**Comment by acodega** [comment]
Curl will follow redirects because it uses the --location option, see line 1500.

Can confirm the Team ID changed.

**Comment by apizz** [comment]
Looks like this is at least partially addressed here: https://github.com/scriptingosx/Installomator/pull/74

**Comment by apizz** [comment]
@scriptingosx does the link actually work now, or is that still borked?

**Comment by scriptingosx** [comment]
As I said in the MacAdmins Slack channel, I believe Brave has an issue in their CDN, in my testing, the download would work about half the time, and throw an error the other half.

**Comment by apizz** [comment]
Got it, didn't see the response in channel.
